### PR TITLE
Sand

### PR DESCRIPTION
**Pull request by hvenev**
It's coarse and rough and irritating and it gets everywhere.

This fixes the build on aarch64 when using `--enable-v4l2-request`. I have not tested 32-bit ARM because I do not believe in 32-bit ARM.

`--enable-rpi` still does not build and I have not made attempts to fix it.

I have not yet tested builds on other platforms.

I did a quick test. `mpv`, when using the DRM backend, seems to be using hardware decoding (verbose logs say so and CPU usage is lower). However, I have not yet been able to inspect the visual output. Also, the CPU usage seems to be suspiciously limited to 100%. I have not yet checked if there is a single-threaded bottleneck.

### CODE REVIEW

**Comment by popcornmix** [comment]
ping @jc-kynesim

**Comment by jc-kynesim** [comment]
I can't really argue with the aarch64 fix though FFmpeg probably has an existing #define that it prefers to use rather than defined(__arm__). (Though I'm almost certainly guilty of this too in other code.)
There are options on CONFIG_SAND
a) we say OK, sand support is always there even if nothing can use it in which case the sand config logic needs to be removed from the config script too.
b) we make sure --enable-sand works on the config line on its own and add appropriate #ifdefs to remove the sand code to hwcontext_drm (and anywhere else I missed)
I personally don't care much either way though I quite like the #defines as they mark where I've edited in the base code base.

Either way hvenvs winge that our userland repo is out of sync with firmware is valid and should be addressed.

**Comment by hvenev** [comment]
Is the SAND code actually required for v4l2-request HEVC? It appears that it is only called when a MMAL-driver-specific pixel format is encountered.

**Comment by popcornmix** [comment]
Was the userland issue resolved by https://github.com/raspberrypi/userland/pull/624 or is there something more?

**Comment by hvenev** [comment]
When building with `--enable-rpi` on aarch64, there is still the problem with `sizeof(VC_IMAGE)`. This pull request is a (not very clean) way to fix the build when `--enable-rpi` is not given.

With kernel headers from https://github.com/raspberrypi/linux/tree/rpi-5.6.y and the latest https://github.com/raspberrypi/userland/ (and this pull request), ffmpeg builds and decoding appears to work, although it appears to be a bit slower than software decoding for 1080p@24 yuv420p10.

**Comment by jc-kynesim** [comment]
If you are doing stuff on a Pi then Yes you need sand as there is only one V4L2 request decoder (HEVC) and the only output format that that supports is sand - if you are on other h/w then no you don't need or want sand - hence my opinion that sand support should be optional.

**Comment by hvenev** [comment]
I think this is a better fix. I tested it and it seems to work. It also builds without `--enable-v4l2-request` on x86_64.

**Comment by hvenev** [comment]
Apparently adding stuff to the middle of `enum AVPixelFormat` breaks ABI.

To fix ABI compatibility with binaries built against upstream ffmpeg, define `AV_PIX_FMT_RPI` _after_ the upstream pixel formats.

**Comment by hvenev** [comment]
Bump?

**Comment by popcornmix** [comment]
@jc-kynesim what do you want to do?
(this repo isn't the upstream, so merging here won't have any long term effect unless @jc-kynesim wants it in his tree).

**Comment by jc-kynesim** [comment]
hvenc has good points re. compiling & I'm certainly going to take his deltas (or something that looks very much like them) into my tree.  My tree is a little untidy at the moment so I'm not going to push a new version to you until it is tidier (or if there is some other reason) so taking his stuff seems like a good idea to me.

**Comment by popcornmix** [comment]
Okay merged here, but may appear in a slightly different form in the future where @jc-kynesim makes a new release.

**Pull request merged**
